### ISSUE TITLE
Semester 1 grade tracker - QCA

### ISSUE THREAD

**Issue by sprince0031** [sprince0031/UL_Masters#56]
This issue is to record my performance in terms of grades achieved for all modules in semester 1 of the course.

## Grades:

- [x] CE4051 - Introduction to Data Engineering and Machine Learning - A1
- [x] CE6021 - Machine Vision - A1
- [x] EE6041 - Text Analytics and Natural Language Processing - A1
- [x] CS4096 - Artificial Intelligence for Games - B1
- [x] CS6271 - Evolutionary Algorithms and Humanoid Robotics - A2
- [x] Qualitative Credits Assessment (QCA) - 3.76/4 (94%)

**Comment by sprince0031** [comment]
#### Machine Vision grade break-up

Assignments carry 45% weight and final exam carries 55% weight.  
Assignments score - 44.5/45  
Exam score - 51/80 -> 63.75% -> Final weightage: 55 * 0.6375 = 35.0625

Final percentage: 44.5 + 35.0625 = 79.5625% (0.44% from 80% which would have given me A1. Hopefully, I might get bumped up 🤞🏼 .)

**Comment by sprince0031** [comment]
#### Introduction to Data Engineering and Machine Learning grade break-up
  
- Assignment 1 - A1 (98.8%)
- Assignment 2 - A2 (88%)
- Assignment 3 - B1 (74.9%)
- Assignment 4 - A1 (94%)
- Assignment 5 - A1 (100%)
- Assignment 6 - A1 (100%)

**Overall grade: A1 (92.02%)**  
I made it to the top two in my class! 😄
