### ISSUE TITLE
Semester 2 grade tracker - QCA

### ISSUE THREAD

**Issue by sprince0031** [sprince0031/UL_Masters#57]
This issue is to record my performance in terms of grades achieved for all modules in semester 2 of the course.

## Grades

- [x] CE6012 - Artificial Intelligence and Machine Learning - A1
- [x] CS6482 - Deep Reinforcement Learning - B1
- [x] CS5024 - Theory and Practice of Advanced AI Ecosystems - A1
- [x] CS6462 - Probabilistic and Explainable AI - A1
- [x] CS6472 - Research Methods and Specification - A1
- [x] QCA - 3.84/4.0
- [x] Cumulative QCA - 3.80/4.0

**Comment by sprince0031** [comment]
## CE6012 - AI and ML grade breakdown:
- E-tivity 1: 7.92 / 8.33 = 95%
- Exam 1: 17.5/20 = 87.5% 
- E-tivity 2: 9.091/10 = 90.91%
- Exam 2: 20/20 = 100%
- E-tivity 3: 6.6/10 = 66% (38/40 in from the rubrics but incurred a 30% late submission penalty)
- Exam 3: 17.75/20 = 88.75%
  
Taking best 5/6, average = (95+87.5+90.91+100+88.75)/5 = 92.432%  
Final grade: A1 (>=90%) => QPV - 4.0

**Comment by sprince0031** [comment]
## CS5024 - Theory & Practice of AI Ecosystems grade breakdown:
- AWS Cloud: 99/100 => 30/30
- AWS ML: 100/100 => 30/30
- Main assignment: 93/100 => 28/30
- Main assignment forum: 80/100 => 8/10

Total weight achieved = 30 + 30 + 28 + 8 => 96%
**Final grade: A1 (>=90%) => QPV - 4.0**

**Comment by sprince0031** [comment]
## 6462 - Probabilistic & Explainable AI grade breakdown:
- Quiz 1: 4/4 - A1
- Assignment 1: 12/12 - A1
- Quiz 2: 2.4/4 - B2
- Quiz 3: 3.6/4 - A1
- Assignment 2: 11.4/12 - A1
- Quiz 4: 1.8/4 - C3
- Forum activity: 4/10 - C3
- Midterm exam: 26.75/30 - A1
- Quiz 5: 3.4/4 - A1
- Assignment 3: 12/12 - A1
- Quiz 6: 3.8/4 - A1

Total weight achieved = 4 + 12 + 2.4 + 3.6 + 11.4 + 1.8 + 4 + 26.75 + 3.4 + 12 + 3.8 => 85.15%
**Final grade: A1 (>=80%) => QPV - 4.0**

**Comment by sprince0031** [comment]
## CS6472 - Research Methods and Specification grade breakdown:
- Assignment 1: 16/20
- Assignment 2: 24/30
- Assignment 3: N/A
- Assignment 4: N/A

Total weight achieved = 16 + 24 + ? + ? >= 80%
**Final grade: A1 (>=80%)**

**Comment by sprince0031** [comment]
## CS6482 - Deep Reinforcement Learning
- Assignment 1: 16/20
- Assignment 2: 7.5/10
- Assignment 3: 15.5./20
- Midterm: 12.5/20
- Final exam: ?/30

Total weight achieved = 16 + 7.5 +15.5 +12.5 + ? >= 64%
**Final grade: B1 (>=64 && <72%)**
